### ISSUE TITLE
Non-edit focus keeps moving to different words after video playback is paused

### ISSUE THREAD

**Issue by MikeRidgway** [lborgman/easy-cap-ed#131]
... making it kind of hard to edit the word that you intended to edit as the keystroke you press will be applied to a different word by the time you press it.

**Comment by lborgman** [comment]
Thanks @MikeRidgway , it looked like I stopped at the wrong place. I think I fixed it now (0.64.75).

Do you still see it?

**Comment by lborgman** [comment]
Hm, the bug is still there.

**Comment by lborgman** [comment]
But now it might be mostly gone. (I'm still hesitating to implement an FSM for this. Too many states. I must be thinking wrong somehow. 🤔)

**Comment by lborgman** [comment]
Hm, no. When I tested an hour ago it worked fine on my mobile, but now"play word" doesn't always start as it should. So there is a timing issue.

**Comment by lborgman** [comment]
Maybe I should say that at the bottom of this problem is the fact that the YouTube video player does not tell you when it has moved to the time you requested. So you have to loop and check to find out when it is ready. However this creates performance problems on a mobile if you do it too fast. And a bad UI if you do it too slow.

**Comment by MikeRidgway** [comment]
Yes, my software has to use similar functionality. A perpetual check to see
if a time point in the video has been reached.

**Comment by lborgman** [comment]
I think this is fixed now. It should be pretty stable. (Though there is one issue with starting to play word while already playing word. It should just restart playing the same word.)
